### ISSUE TITLE
Needs declaration for `__exit__`

### ISSUE THREAD

**Issue by jwodder** [charmoniumQ/tqdm-stubs#1]
The declarations for `tqdm` in this package have it inherit [`typing.ContextManager`](https://docs.python.org/3.11/library/typing.html#typing.ContextManager), which is a generic version of [`contextlib.AbstractContextManager`](https://docs.python.org/3.11/library/contextlib.html#contextlib.AbstractContextManager), which declares `__exit__` as an abstract method.  As this package does not define a stub for `__exit__`, mypy assumes that tqdm does not override the abstract method and is thus an abstract class.  As a result, this code:

```python
from tqdm import tqdm

t = tqdm(total=1000)
```

fails to type-check with mypy 0.961 and tqdm-stubs 0.2.0, giving the error:

```
tqdm-stubs.py:3: error: Cannot instantiate abstract class "tqdm" with abstract attribute "__exit__"
```

**Comment by charmoniumQ** [comment]
I'll look at this tomorrow.

**Comment by charmoniumQ** [comment]
This is due to a difference between Mypy 0.910 and Mypy 0.961.

I upgraded my test suite to Mypy 0.961, added the test case to the test suite, and fixed this error.

Try upgrading to type-stubs 0.2.1.

**Comment by jwodder** [comment]
It works now; thanks!
